steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'us-central1-docker.pkg.dev/trusty-sentinel-412713/pythonrepo/my-app:${SHORT_SHA}',
            '-t',
            'us-central1-docker.pkg.dev/trusty-sentinel-412713/pythonrepo/my-app:latest',
            '--cache-from',
            'us-central1-docker.pkg.dev/trusty-sentinel-412713/pythonrepo/my-app:latest',
            '.'
          ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/trusty-sentinel-412713/pythonrepo/my-app:${SHORT_SHA}']

# Store images in Google Artifact Registry 
images:
  - us-central1-docker.pkg.dev/trusty-sentinel-412713/pythonrepo/my-app:${SHORT_SHA}
  - us-central1-docker.pkg.dev/trusty-sentinel-412713/pythonrepo/my-app:latest
  
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --image=us-central1-docker.pkg.dev/trusty-sentinel-412713/pythonrepo/my-app:${SHORT_SHA}
  - --location=us-central1
  - --cluster=pythontest-cluster-1
